/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check
 
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  docsSidebar: [
    'intro',
    'guide',
    'cgu',
    'cgu-discord',
    {
      type: 'category',
      label: 'Nouvautées',
      items: [
        {
          type: 'autogenerated',
          dirName: 'new',
        },
      ],
    },
    {
      type: 'category',
      label: 'Dashboard',
      items: [
        'dashboard/overview',
        'dashboard/getting-started',
        'dashboard/customization',
        'dashboard/errors',
      ],
    },
    'style',
    'changelog',
  ],
  guideSidebar: [
    'guide/intro',
    {
      type: 'category',
      label: 'Site Web',
      items: [
        {
          type: 'autogenerated',
          dirName: 'guide/website',
        },
      ],
    },

    {
      type: 'category',
      label: 'Bot Discord',
      items: [
        {
          type: 'autogenerated',
          dirName: 'guide/botdiscord',
        },
      ],
    },
    {
      type: 'category',
      label: 'Logiciel',
      items: [
        {
          type: 'autogenerated',
          dirName: 'guide/logiciel',
        },
      ],
    },

  ],
  apiSidebar: [
    'api/intro',
    'api/start',
    'api/authentification',
    {
      type: 'category',
      label: 'Endpoints',
      items: [
        {
          type: 'autogenerated',
          dirName: 'api/endpoints',
        },
      ],
    },
    'api/changelog',
    'api/use-cases',
    'api/faq',
  ],
  communitySidebar: [
    'support/intro',
    'support/contact',
    'support/staff',
    'support/Evenements_et_Concours',
    'support/Temoignages',
    'support/Success_Stories',
    'support/partner',
    'support/rex',
  ],





};

export default sidebars;
